/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ventana;

import proyecto2.Central;

/**
 *
 * @author Yarixa
 */
public class VentanaEmpresa extends javax.swing.JFrame {
    private int opcion;
    private int g93;
    private int g95;
    private int g97;
    private int diesel;
    private int kerosene;
    private Central central;
    /**
     * Creates new form VentanaEmpresa
     */
    public VentanaEmpresa() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        option93 = new javax.swing.JRadioButton();
        option95 = new javax.swing.JRadioButton();
        optionKerosene = new javax.swing.JRadioButton();
        option97 = new javax.swing.JRadioButton();
        optionDiesel = new javax.swing.JRadioButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        actual93 = new javax.swing.JTextField();
        actual95 = new javax.swing.JTextField();
        actual07 = new javax.swing.JTextField();
        actualDiesel = new javax.swing.JTextField();
        actualKerosene = new javax.swing.JTextField();
        nuevo93 = new javax.swing.JTextField();
        nuevo95 = new javax.swing.JTextField();
        nuevo97 = new javax.swing.JTextField();
        nuevoDiesel = new javax.swing.JTextField();
        nuevoKerosene = new javax.swing.JTextField();
        botonGenerarReporte = new javax.swing.JButton();
        botonGuardar1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel1.setText("Central");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setText("Cambiar Precio");

        option93.setText("93");
        option93.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                option93ActionPerformed(evt);
            }
        });

        option95.setText("95");
        option95.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                option95ActionPerformed(evt);
            }
        });

        optionKerosene.setText("Kerosene");
        optionKerosene.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                optionKeroseneActionPerformed(evt);
            }
        });

        option97.setText("97");
        option97.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                option97ActionPerformed(evt);
            }
        });

        optionDiesel.setText("Diesel");
        optionDiesel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                optionDieselActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setText("Tipo Combustible");

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setText("Precio Actual");

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel5.setText("Precio Nuevo");

        actual93.setText(" ");

        actual95.setText(" ");

        actual07.setText(" ");

        actualDiesel.setText(" ");

        actualKerosene.setText(" ");

        nuevo93.setText(" ");
        nuevo93.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nuevo93ActionPerformed(evt);
            }
        });

        nuevo95.setText(" ");
        nuevo95.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nuevo95ActionPerformed(evt);
            }
        });

        nuevo97.setText(" ");
        nuevo97.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nuevo97ActionPerformed(evt);
            }
        });

        nuevoDiesel.setText(" ");
        nuevoDiesel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nuevoDieselActionPerformed(evt);
            }
        });

        nuevoKerosene.setText(" ");
        nuevoKerosene.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nuevoKeroseneActionPerformed(evt);
            }
        });

        botonGenerarReporte.setText("Generar Reporte");
        botonGenerarReporte.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonGenerarReporteActionPerformed(evt);
            }
        });

        botonGuardar1.setText("Guardar Cambios");
        botonGuardar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonGuardar1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(126, 126, 126)
                        .addComponent(jLabel1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3)
                                    .addComponent(option93)
                                    .addComponent(option95)
                                    .addComponent(option97)
                                    .addComponent(optionDiesel)
                                    .addComponent(optionKerosene))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 33, Short.MAX_VALUE)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(actual93, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 66, Short.MAX_VALUE)
                                        .addComponent(actual95, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(actual07, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(actualDiesel, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(actualKerosene, javax.swing.GroupLayout.Alignment.LEADING)))
                                .addGap(53, 53, 53)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel5)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(nuevo93, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(nuevo95, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(nuevo97, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(nuevoDiesel, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(nuevoKerosene, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(24, 24, 24)
                                        .addComponent(botonGuardar1)))
                                .addGap(0, 0, Short.MAX_VALUE)))))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(botonGenerarReporte)
                .addGap(46, 46, 46))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addGap(13, 13, 13)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(option93)
                            .addComponent(actual93, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(option95)
                            .addComponent(actual95, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(option97)
                            .addComponent(actual07, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(optionDiesel)
                            .addComponent(actualDiesel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(optionKerosene)
                            .addComponent(actualKerosene, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(nuevo93, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(nuevo95, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(nuevo97, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(nuevoDiesel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(nuevoKerosene, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botonGenerarReporte)
                    .addComponent(botonGuardar1))
                .addContainerGap(18, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void option93ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_option93ActionPerformed
        // TODO add your handling code here:
        this.opcion=1;
        System.out.println("opcion 1");
    }//GEN-LAST:event_option93ActionPerformed

    private void option95ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_option95ActionPerformed
        // TODO add your handling code here:
        this.opcion=2;
    }//GEN-LAST:event_option95ActionPerformed

    private void nuevo95ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nuevo95ActionPerformed
        this.g95=Integer.valueOf(nuevo95.getText());
        
    }//GEN-LAST:event_nuevo95ActionPerformed

    private void option97ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_option97ActionPerformed
        // TODO add your handling code here:
        this.opcion=3;
    }//GEN-LAST:event_option97ActionPerformed

    private void optionDieselActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_optionDieselActionPerformed
        // TODO add your handling code here:
        this.opcion=4;
    }//GEN-LAST:event_optionDieselActionPerformed

    private void optionKeroseneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_optionKeroseneActionPerformed
        // TODO add your handling code here:
        this.opcion=5;
    }//GEN-LAST:event_optionKeroseneActionPerformed

    private void botonGenerarReporteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonGenerarReporteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_botonGenerarReporteActionPerformed

    private void botonGuardar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonGuardar1ActionPerformed
        // TODO add your handling code here:
        if(option95.isSelected()){
            
        }
    }//GEN-LAST:event_botonGuardar1ActionPerformed

    private void nuevo93ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nuevo93ActionPerformed
        g93=Integer.valueOf(nuevo93.getText());   
        System.out.println("Nuevo uno");
    }//GEN-LAST:event_nuevo93ActionPerformed

    private void nuevo97ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nuevo97ActionPerformed
        // TODO add your handling code here:
        this.g97=Integer.valueOf(nuevo97.getText());
    }//GEN-LAST:event_nuevo97ActionPerformed

    private void nuevoDieselActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nuevoDieselActionPerformed
        this.diesel=Integer.valueOf(nuevoDiesel.getText());        // TODO add your handling code here:
    }//GEN-LAST:event_nuevoDieselActionPerformed

    private void nuevoKeroseneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nuevoKeroseneActionPerformed
        this.kerosene=Integer.valueOf(nuevoKerosene.getText());
        // TODO add your handling code here:
    }//GEN-LAST:event_nuevoKeroseneActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaEmpresa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaEmpresa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaEmpresa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaEmpresa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaEmpresa().setVisible(true);
            }
        });
    
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField actual07;
    private javax.swing.JTextField actual93;
    private javax.swing.JTextField actual95;
    private javax.swing.JTextField actualDiesel;
    private javax.swing.JTextField actualKerosene;
    private javax.swing.JButton botonGenerarReporte;
    private javax.swing.JButton botonGuardar1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField nuevo93;
    private javax.swing.JTextField nuevo95;
    private javax.swing.JTextField nuevo97;
    private javax.swing.JTextField nuevoDiesel;
    private javax.swing.JTextField nuevoKerosene;
    private javax.swing.JRadioButton option93;
    private javax.swing.JRadioButton option95;
    private javax.swing.JRadioButton option97;
    private javax.swing.JRadioButton optionDiesel;
    private javax.swing.JRadioButton optionKerosene;
    // End of variables declaration//GEN-END:variables
}
